on:
  workflow_dispatch:

env:
  time_limit_minutes: 30

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./github/actions/test@v1
        with:
          time_limit_minutes: ${{ env.time_limit_minutes }}
